// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RabaniCRMAssigment.Data;

namespace RabaniCRMAssigment.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("RabaniCRMAssigment.Models.Accounts", b =>
                {
                    b.Property<int>("AccountsId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AppUserID");

                    b.Property<int>("Balance");

                    b.Property<string>("Name");

                    b.Property<string>("Status");

                    b.HasKey("AccountsId");

                    b.HasIndex("AppUserID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("RabaniCRMAssigment.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("AppUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RabaniCRMAssigment.Models.Rewards", b =>
                {
                    b.Property<int>("RewardsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RewardName");

                    b.Property<int>("RewardPoint");

                    b.HasKey("RewardsId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("RabaniCRMAssigment.Models.Services", b =>
                {
                    b.Property<int>("ServicesId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<int>("PointsEarned");

                    b.Property<string>("ServiceName");

                    b.HasKey("ServicesId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("RabaniCRMAssigment.Models.Accounts", b =>
                {
                    b.HasOne("RabaniCRMAssigment.Models.AppUser", "appUser")
                        .WithMany("Accounts")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
